export type MvDevolucion = {
    devonum: number;
    fecemis: Date;
    estatus: string;
    codcli: string;
    clides: string;
    codven: string;
    vendes: string;
    comentario?: string | null;
    codart?: string | null;
    artdes?: string | null;
    codbarra?: string | null;
    serial?: string | null;
    // registradopor?: string | null;
    // fecharegistro: Date;
    // recibidopor?: string | null;
    // fecharecibido: Date;
    // observarcbo?: string | null;
    // motivo: string;
    // tipo: number;
    // chofer: string;
    // inspeccionpor?: string | null;
    // fechainspeccion: Date;
    // observainsp?: string | null;
    // tecnicopor?: string | null;
    // fechatecnico: Date; 
    // observatnco?: string | null;
    // clasificacion: string;
    imgart?: string | null;
};